name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  speech_to_text: ^7.0.0-beta.1
  image_picker: ^1.0.7 # Added image_picker
  url_launcher: ^6.2.1 # Added url_launcher

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: FontMain
      fonts:
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf

# ⚠️ VERY IMPORTANT:
# This must be at ROOT LEVEL (same level as name:, dependencies:)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF" # Add background for adaptive icons
  adaptive_icon_foreground: "assets/images/app_logo.png" # Explicitly set foreground

flutter_native_splash:
  color: "#FFFFFF"
  #  image: assets/images/logo.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#FFFFFF"
#    image: assets/images/logo.png
